apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "app.name" .}}
  labels:
    app.kubernetes.io/name: {{include "app.name" .}}
    helm.sh/chart: {{include "app.chart" .}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
spec:
  replicas: {{.Values.replicas}}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
      {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ include "app.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: {{ .Values.container.healthCheck }}
            port: {{ .Values.container.port }}
          initialDelaySeconds: 10
          periodSeconds: 30
        {{- if .Values.container.env }}
        env:
          {{- range .Values.container.env }}
          - name: {{ .name }}
            {{- if .value }}
            value: {{ .value | quote }}
            {{- end}}
            {{- if .valueFrom }}
            valueFrom:
              secretKeyRef:
                name: {{.valueFrom.secretKeyRef.name}}
                key: {{.valueFrom.secretKeyRef.key}}
            {{- end}}
          {{- end }}
        {{- end }}
        {{- if .Values.container.envFrom}}
        envFrom:
          {{- range .Values.container.envFrom }}
          - secretRef:
              name: {{ .secretRef.name }}
          {{- end}}
        {{- end }}
        ports:
          - name: http
            containerPort: {{ .Values.container.port }}
        {{- if .Values.container.volumeMounts }}
        volumeMounts:
          {{- toYaml .Values.container.volumeMounts | nindent 10 }}
        {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end}}
